version: "3.9"

services:
  db:
    image: postgres
    env_file:
      .env
    environment:
      - POSTGRES_DB=totallywired
      - POSTGRES_USER=totallywired
    ports:
      - 5432:5432
  web:
    build: .
    env_file:
      .env
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
