# Generated by Django 3.1 on 2020-08-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='type',
            new_name='provider',
        ),
    ]
