# Generated by Django 3.1 on 2020-08-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20200819_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='providers.artist')),
            ],
            options={
                'ordering': ('year',),
            },
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='provider',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('artist_credit', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('length', models.PositiveIntegerField()),
                ('bitrate', models.PositiveSmallIntegerField(null=True)),
                ('provider', models.CharField(max_length=8)),
                ('download_url', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tracks', to='providers.artist')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='providers.release')),
            ],
            options={
                'ordering': ('disc', 'position'),
            },
        ),
    ]
