# Generated by Django 3.1 on 2020-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_track_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='download_url',
        ),
        migrations.AddField(
            model_name='track',
            name='provider_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
