# Generated by Django 3.1 on 2020-08-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0005_auto_20200819_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_artists', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_releases', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to='auth.user'),
            preserve_default=False,
        ),
    ]
