# Generated by Django 3.1 on 2020-08-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20200819_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
    ]
