# Generated by Django 3.1 on 2020-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_release_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
    ]
