# Generated by Django 3.1 on 2020-08-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_artist_thumbnail_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('artist__name', 'release__name', 'disc', 'position')},
        ),
        migrations.AddField(
            model_name='track',
            name='length_display',
            field=models.CharField(default='1:00', max_length=50),
            preserve_default=False,
        ),
    ]
