# Generated by Django 3.1 on 2020-08-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20200820_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
