# Generated by Django 3.1 on 2020-08-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_track_release_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
    ]
