# Generated by Django 3.1 on 2020-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_track_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='thumbnail_url',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='release',
            name='thumbnail_url',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='thumbnail_url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
