# Generated by Django 3.1 on 2020-08-20 22:34

from django.db import migrations, models
import providers.common.caching


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_auto_20200820_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=providers.common.caching.release_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='track',
            name='thumbnail',
            field=models.TextField(default=''),
        ),
    ]
