# Generated by Django 3.1 on 2020-08-20 22:43

from django.db import migrations, models
import providers.common.caching


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_auto_20200820_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='thumbnail',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='release',
            name='thumbnail',
            field=models.FileField(max_length=255, null=True, upload_to=providers.common.caching.release_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='track',
            name='thumbnail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
