# Generated by Django 3.1 on 2020-08-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0016_track_liked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ('artist__name', 'name')},
        ),
        migrations.AlterField(
            model_name='track',
            name='thumbnail',
            field=models.CharField(default='', help_text='This is a copy of the related release thumbnail.url', max_length=255),
        ),
    ]
