# Generated by Django 3.1 on 2020-09-06 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.common.caching


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.FileField(max_length=255, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('thumbnail', models.FileField(max_length=255, null=True, upload_to=server.common.caching.release_thumbnail_upload_to)),
                ('provider', models.CharField(max_length=8)),
                ('provider_id', models.CharField(default='', max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='server.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('artist__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('release_name', models.CharField(max_length=255)),
                ('artist_credit', models.CharField(max_length=255)),
                ('genre', models.CharField(default='', max_length=255)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('thumbnail', models.CharField(default='', help_text='This is a copy of the related release thumbnail.url', max_length=255)),
                ('length', models.PositiveIntegerField()),
                ('length_display', models.CharField(max_length=50)),
                ('bitrate', models.PositiveSmallIntegerField(null=True)),
                ('liked', models.BooleanField(default=False)),
                ('provider', models.CharField(max_length=8)),
                ('provider_id', models.CharField(default='', max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tracks', to='server.artist')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='server.release')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('artist__name', 'release_name', 'disc', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=8)),
                ('value', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
