# Generated by Django 3.1 on 2020-09-15 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200914_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltrack',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channeltrack',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
